/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SuiButton {
    }
    interface SuiFoo {
        "name": string;
    }
    interface SuiHeadline1 {
    }
    interface SuiHeadline2 {
    }
}
declare global {
    interface HTMLSuiButtonElement extends Components.SuiButton, HTMLStencilElement {
    }
    var HTMLSuiButtonElement: {
        prototype: HTMLSuiButtonElement;
        new (): HTMLSuiButtonElement;
    };
    interface HTMLSuiFooElement extends Components.SuiFoo, HTMLStencilElement {
    }
    var HTMLSuiFooElement: {
        prototype: HTMLSuiFooElement;
        new (): HTMLSuiFooElement;
    };
    interface HTMLSuiHeadline1Element extends Components.SuiHeadline1, HTMLStencilElement {
    }
    var HTMLSuiHeadline1Element: {
        prototype: HTMLSuiHeadline1Element;
        new (): HTMLSuiHeadline1Element;
    };
    interface HTMLSuiHeadline2Element extends Components.SuiHeadline2, HTMLStencilElement {
    }
    var HTMLSuiHeadline2Element: {
        prototype: HTMLSuiHeadline2Element;
        new (): HTMLSuiHeadline2Element;
    };
    interface HTMLElementTagNameMap {
        "sui-button": HTMLSuiButtonElement;
        "sui-foo": HTMLSuiFooElement;
        "sui-headline1": HTMLSuiHeadline1Element;
        "sui-headline2": HTMLSuiHeadline2Element;
    }
}
declare namespace LocalJSX {
    interface SuiButton {
    }
    interface SuiFoo {
        "name"?: string;
        "onClicked"?: (event: CustomEvent<string>) => void;
    }
    interface SuiHeadline1 {
    }
    interface SuiHeadline2 {
    }
    interface IntrinsicElements {
        "sui-button": SuiButton;
        "sui-foo": SuiFoo;
        "sui-headline1": SuiHeadline1;
        "sui-headline2": SuiHeadline2;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sui-button": LocalJSX.SuiButton & JSXBase.HTMLAttributes<HTMLSuiButtonElement>;
            "sui-foo": LocalJSX.SuiFoo & JSXBase.HTMLAttributes<HTMLSuiFooElement>;
            "sui-headline1": LocalJSX.SuiHeadline1 & JSXBase.HTMLAttributes<HTMLSuiHeadline1Element>;
            "sui-headline2": LocalJSX.SuiHeadline2 & JSXBase.HTMLAttributes<HTMLSuiHeadline2Element>;
        }
    }
}
